// <auto-generated />
using System;
using BackendCrab.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendCrab.DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendCrab.EntityLayer.Entitites.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoundationYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street",
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7425),
                            FoundationYear = 2000,
                            IsDeleted = false,
                            Name = "ABC Ltd.",
                            Phone = "123-456-7890",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Avenue",
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7437),
                            FoundationYear = 1995,
                            IsDeleted = false,
                            Name = "XYZ Corp.",
                            Phone = "987-654-3210",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Elm Street",
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7439),
                            FoundationYear = 1988,
                            IsDeleted = false,
                            Name = "Acme Inc.",
                            Phone = "555-123-4567",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Pine Street",
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7498),
                            FoundationYear = 2005,
                            IsDeleted = false,
                            Name = "Global Tech",
                            Phone = "555-987-6543",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "555 Cedar Avenue",
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7499),
                            FoundationYear = 1999,
                            IsDeleted = false,
                            Name = "Sunrise Enterprises",
                            Phone = "555-222-3333",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "777 Beach Boulevard",
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7501),
                            FoundationYear = 2010,
                            IsDeleted = false,
                            Name = "Oceanic Group",
                            Phone = "555-444-5555",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Address = "999 Summit Road",
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7502),
                            FoundationYear = 1990,
                            IsDeleted = false,
                            Name = "Mountain View Inc.",
                            Phone = "555-666-7777",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Address = "222 Ridge Street",
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7503),
                            FoundationYear = 2008,
                            IsDeleted = false,
                            Name = "Dynamic Solutions",
                            Phone = "555-888-9999",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Address = "444 Summit Avenue",
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7504),
                            FoundationYear = 2002,
                            IsDeleted = false,
                            Name = "Pinnacle Enterprises",
                            Phone = "555-000-1111",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Address = "888 Oak Street",
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7505),
                            FoundationYear = 1997,
                            IsDeleted = false,
                            Name = "Evergreen Technologies",
                            Phone = "555-777-8888",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BackendCrab.EntityLayer.Entitites.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7715),
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            Mail = "john.doe@abc.com",
                            Phone = "111-222-3333",
                            Title = "Software Developer",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Age = 35,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7718),
                            FirstName = "Alice",
                            IsDeleted = false,
                            LastName = "Smith",
                            Mail = "alice.smith@abc.com",
                            Phone = "444-555-6666",
                            Title = "HR Manager",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Age = 28,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7720),
                            FirstName = "Michael",
                            IsDeleted = false,
                            LastName = "Johnson",
                            Mail = "michael.johnson@xyz.com",
                            Phone = "777-888-9999",
                            Title = "Sales Representative",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Age = 32,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7721),
                            FirstName = "Emily",
                            IsDeleted = false,
                            LastName = "Brown",
                            Mail = "emily.brown@xyz.com",
                            Phone = "222-333-4444",
                            Title = "Marketing Manager",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Age = 40,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7722),
                            FirstName = "David",
                            IsDeleted = false,
                            LastName = "Wilson",
                            Mail = "david.wilson@def.com",
                            Phone = "555-111-2222",
                            Title = "Project Manager",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Age = 27,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7724),
                            FirstName = "Emma",
                            IsDeleted = false,
                            LastName = "Johnson",
                            Mail = "emma.johnson@def.com",
                            Phone = "555-333-4444",
                            Title = "Financial Analyst",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Age = 35,
                            CompanyId = 4,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7725),
                            FirstName = "Christopher",
                            IsDeleted = false,
                            LastName = "Miller",
                            Mail = "christopher.miller@ghi.com",
                            Phone = "555-555-6666",
                            Title = "Sales Manager",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Age = 25,
                            CompanyId = 4,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7727),
                            FirstName = "Sophia",
                            IsDeleted = false,
                            LastName = "Davis",
                            Mail = "sophia.davis@ghi.com",
                            Phone = "555-777-8888",
                            Title = "Customer Service Representative",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Age = 38,
                            CompanyId = 5,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7728),
                            FirstName = "Matthew",
                            IsDeleted = false,
                            LastName = "Taylor",
                            Mail = "matthew.taylor@jkl.com",
                            Phone = "555-999-0000",
                            Title = "Product Manager",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Age = 29,
                            CompanyId = 5,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7730),
                            FirstName = "Olivia",
                            IsDeleted = false,
                            LastName = "Anderson",
                            Mail = "olivia.anderson@jkl.com",
                            Phone = "555-222-3333",
                            Title = "Marketing Coordinator",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Age = 33,
                            CompanyId = 6,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7731),
                            FirstName = "Daniel",
                            IsDeleted = false,
                            LastName = "Thomas",
                            Mail = "daniel.thomas@mno.com",
                            Phone = "555-444-5555",
                            Title = "IT Specialist",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Age = 31,
                            CompanyId = 6,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7733),
                            FirstName = "Ava",
                            IsDeleted = false,
                            LastName = "White",
                            Mail = "ava.white@mno.com",
                            Phone = "555-666-7777",
                            Title = "Operations Manager",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Age = 36,
                            CompanyId = 7,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7734),
                            FirstName = "William",
                            IsDeleted = false,
                            LastName = "Martinez",
                            Mail = "william.martinez@pqr.com",
                            Phone = "555-888-9999",
                            Title = "HR Coordinator",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Age = 26,
                            CompanyId = 7,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7735),
                            FirstName = "Mia",
                            IsDeleted = false,
                            LastName = "Garcia",
                            Mail = "mia.garcia@pqr.com",
                            Phone = "555-000-1111",
                            Title = "Accountant",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Age = 29,
                            CompanyId = 8,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7737),
                            FirstName = "James",
                            IsDeleted = false,
                            LastName = "Hernandez",
                            Mail = "james.hernandez@stu.com",
                            Phone = "555-222-3333",
                            Title = "Software Engineer",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Age = 24,
                            CompanyId = 8,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7738),
                            FirstName = "Charlotte",
                            IsDeleted = false,
                            LastName = "Lopez",
                            Mail = "charlotte.lopez@stu.com",
                            Phone = "555-444-5555",
                            Title = "QA Tester",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Age = 34,
                            CompanyId = 9,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7740),
                            FirstName = "Benjamin",
                            IsDeleted = false,
                            LastName = "Gonzalez",
                            Mail = "benjamin.gonzalez@vwx.com",
                            Phone = "555-666-7777",
                            Title = "Financial Analyst",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Age = 27,
                            CompanyId = 9,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7741),
                            FirstName = "Amelia",
                            IsDeleted = false,
                            LastName = "Rodriguez",
                            Mail = "amelia.rodriguez@vwx.com",
                            Phone = "555-888-9999",
                            Title = "Marketing Specialist",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Age = 37,
                            CompanyId = 10,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7742),
                            FirstName = "Ethan",
                            IsDeleted = false,
                            LastName = "Smith",
                            Mail = "ethan.smith@yz.com",
                            Phone = "555-111-2222",
                            Title = "IT Manager",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Age = 32,
                            CompanyId = 10,
                            CreatedDate = new DateTime(2024, 3, 29, 0, 37, 33, 880, DateTimeKind.Local).AddTicks(7744),
                            FirstName = "Isabella",
                            IsDeleted = false,
                            LastName = "Lee",
                            Mail = "isabella.lee@yz.com",
                            Phone = "555-333-4444",
                            Title = "HR Director",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BackendCrab.EntityLayer.Entitites.Employee", b =>
                {
                    b.HasOne("BackendCrab.EntityLayer.Entitites.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BackendCrab.EntityLayer.Entitites.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
